---

- name: Ensure the key path exists
  file:
    path={{deploy_key_client_key_path}}
    state=directory
    owner={{deploy_key_client_user}}
    group={{deploy_key_client_group}}
    mode=0700

- name: Install deployment key.
  copy:
    src={{deploy_key_assets_path}}/{{deploy_key_name}}
    dest={{deploy_key_client_key_path}}/{{deploy_key_name}}
    owner={{deploy_key_client_user}}
    group={{deploy_key_client_group}}
    mode=600

- name: Strip passphrase from key.
  shell: ssh-keygen -p -P '{{ssh_key_passphrase}}' -N '' -f {{deploy_key_client_key_path}}/{{deploy_key_name}}
